### ISSUE TITLE
Issue with child themes and primary color

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/oblique#108] opened 2018-03-11 23:31 UTC
When a child theme is used the primary color shows that it's changed in the customizer preview but upon saving the change isn't actually reflected.

I think this might have something to do with the child theme's function.php code 

@HardeepAsrani @rodica-andronache

**Comment by rodica-andronache** [comment] 2018-03-12 09:30
@UVLabs if it's related to the child theme, maybe it would be better to also mention the child theme you tested with :D

**Comment by netlots** [comment] 2018-03-12 18:58
@rodica-andronache UVLabs is a support officer that is trying to help me with a theme I purchased called Oblique Pro from ThemeIsle, and I followed ThemeIsle's documentation on creating a child theme for it. https://docs.themeisle.com/article/14-how-to-create-a-child-theme. 
The problem is as UVLabs describes, while using the Customizer I can see the Primary Colour change on screen but it reverts back to the default colour as soon as I publish the settings.
If I activate the parent theme, it works fine. I would be very helpful if you can help fix this problem.

**Comment by rodica-andronache** [comment] 2018-03-13 14:41
Hi @netlots ,

Thank you for the details. I checked the doc and you are right, there is a problem with the colors. 
The problem is that the doc is a general one, and some of the themes are built a little bit different than the others. That's why they require some tweaking. In this case, changing the 99 in this line `add_action( 'wp_enqueue_scripts', 'child_enqueue_styles',99);` with a 10, it's the way to go. 
Could you please let me know if that helps.
I'll update the doc too.

Regards,
Rodica

**Comment by netlots** [comment] 2018-03-15 03:28
Hi @rodica-andronache, thank you for that.
That worked fine. I had also made some additional minor style adjustments, (colours of hovers etc), but I did those in the Style.css, not the Additional CSS section of the Customiser and I was surprised that the changes did work as expected before I changed the '99' to a '10', but did not work after the change. But when I transferred them to the Additional CSS section in the customiser, they worked. It kinda makes sense, even though I don't understand it. Just thought I'd mention it because I thought they should work in the style css all the same, no? 
Is there a way I can turn off the prev & next post buttons in the single post display? 
Thanx in advance.

**Comment by rodica-andronache** [comment] 2018-03-15 09:21
Hi @netlots,

Yes, all the changes should be work from the style.css file of your child theme too. I tried changing some colors for some of the elements and didn't have a problem with that. Sure, for some elements, it's possible that you'd also need to use the !important tag, for example:
`.entry-title a {
	color: blue !important;
}`
to be sure that property is overwritten.
But it should all work. Could you please share your website so I can see exactly what do you mean by turning off the prev and next post buttons? Do you want to hide them? 
If that's so, you just need to add this code in the style.css file of your child theme:
`.single .navigation.post-navigation {
    display: none;
}`
Let me know if that helps.
Regards,
Rodica

**Comment by netlots** [comment] 2018-03-15 09:48
Hi @rodica-andronache, fantastic. yes sure, it's https://www.chocolatefestival.co.nz/2018/

I didn't know that the !important helps to ensure stuff is properly overwritten, thanks for letting me know.
The stuff that wasn't working when it was in the style.css, was for example
`.entry-thumb:after {
	position: absolute;
	bottom: 0;
	left: 0;
	width: 100%;
	height: 0;
	background-color: rgba(35, 182, 182, 0.0);
	content: "";
	-webkit-transition: height 0.4s;
	transition: height 0.4s;`

I changed the alpha from 0.4 to 0.0, because I didn't know how to get rid of that effect ... (embarrased, I know nothing about how to code properly, mmmh).

And thanks for the single post navigation stuff, yes, I was looking to remove the 'previous' and 'next' post buttons. Actually looking for some sort of 'related post function'. Instead.
I tried Jetpack, which related post feature did exactly what I wanted and looked the part but it slowed down the site to a crawl, so I turned it off again.

But I think the theme looks really great, are you the author? if so, thanks, and thanks anyway for helping me.

Do you have any advice on how I can get some more help making minor modifications to the layout
Such as adding a 'related posts by category feature' or looking to change the amount of padding that 'below header widget' has. Or moving that widget to show up below the posts, instead of above.
Regards
netlots

**Comment by rodica-andronache** [comment] 2018-03-15 12:25
Hi @netlots ,

No problem, really happy to help :)
If you have Oblique Pro, you can contact us here https://themeisle.com/contact/ and find out what our support can offer. Usually, custom coding is not covered by this, but you can talk more about with my colleagues on support.

Regards,
Rodica

**Closed as completed** 2018-03-21 11:02 UTC
